[FLOORDES]
#Files=  1
File1=FloorDes.DXF
Description1=Floor System Layout
[ROOFDES]
#Files=  3
File1=RoofDes.DXF
Description1=Roof Design
File2=RoofZone1.DXF
Description2=Roof Panel Zone 1
File3=RoofZone2.DXF
Description3=Roof Panel Zone 2
[PARTDES]
#Files=  1
File1=PartDes.DXF
Description1=Partition Walls
[EWDES-L]
#Files=  1
File1=EwDes-L.DXF
Description1=Left Endwall Design
[EWDES-R]
#Files=  1
File1=EwDes-R.DXF
Description1=Right Endwall Design
[DESCALC]
#Files=  3
File1=DesCalc.DXF
Description1=Panel Zone: Wind 1
File2=DesCalc2.DXF
Description2=Panel Zone: Wind 2
File3=DesCalc3.DXF
Description3=Panel Zone: Wind 3
[FLOORDET]
#Files=  1
File1=FLOORDET.DXF
Description1=Floor System Layout
[BOM]
#Files=  3
File1=BOMext1.DXF
Description1=Extension 1
File2=BOMext2.DXF
Description2=Extension 2
File3=BOMext3.DXF
Description3=Extension 3
[DESCTRL]
#Files=  2
File1=DesCtrl.DXF
Description1=Building Layout
File2=Layout.DXF
Description2=Frame Layout
